// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MC.Data.Entities;

public partial class Menu
{
    public Guid ID { get; set; }

    public Guid? ParentID { get; set; }

    public string Caption { get; set; }

    public string Path { get; set; }

    public string Icon { get; set; }

    public string Roles { get; set; }
}