// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MC.Data.Entities;

public partial class Resource
{
    public Guid ID { get; set; }

    public string Key { get; set; }

    public string Language { get; set; }

    public string Value { get; set; }
}