// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MC.Data.Entities;

public partial class State
{
    public Guid ID { get; set; }

    public string Caption { get; set; }

    public string Description { get; set; }

    public int CodeStart { get; set; }

    public int CodeEnd { get; set; }

    public DateTime CreationDate { get; set; }

    public virtual ICollection<StateColumn> StateColumn { get; set; } = new List<StateColumn>();
}