// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MC.Data.Entities;

public partial class StateRow
{
    public Guid ID { get; set; }

    public Guid StateID { get; set; }

    public int CodeStart { get; set; }

    public int CodeEnd { get; set; }

    public virtual State State { get; set; }
}