// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MC.Data.Entities;

public partial class StateColumn
{
    public Guid ID { get; set; }

    public Guid StateID { get; set; }

    public int Position { get; set; }

    public string Caption { get; set; }

    public string Code { get; set; }

    public virtual State State { get; set; }
}