// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MC.Data.Entities;

public partial class UserRole
{
    public Guid ID { get; set; }

    public Guid UserID { get; set; }

    public short Role { get; set; }

    public virtual User User { get; set; }
}