// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MC.Data.Entities;

public partial class User
{
    public Guid ID { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime RegistrationDate { get; set; }

    public virtual ICollection<UserPassword> UserPassword { get; set; } = new List<UserPassword>();

    public virtual ICollection<UserRole> UserRole { get; set; } = new List<UserRole>();

    public virtual ICollection<UserStatus> UserStatus { get; set; } = new List<UserStatus>();
}